version: '2'
machine:
  - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci
  - pip install docker-compose==1.8.0
services:
 db:
   image: postgres
 web:
   build: .
   command: python django-polls/manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/srv
   ports:
     - "8000:8000"
   depends_on:
     - db